// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CT01AcessandoHomeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT01AcessandoHome() {
    driver.get("https://www.webmotors.com.br//");
    driver.findElement(By.id("searchBar")).click();
    driver.findElement(By.id("searchBar")).sendKeys("Honda City");
    driver.findElement(By.cssSelector(".SearchBar__results__result__name")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".NavBar"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".Filters__line--gray")).click();
    driver.findElement(By.linkText("1.5 EX 16V FLEX 4P AUTOMÁTICO")).click();
    driver.get("https://www.webmotors.com.br//");
    driver.findElement(By.id("searchBar")).click();
    driver.findElement(By.id("searchBar")).sendKeys("carro");
    assertThat(driver.findElement(By.cssSelector(".SearchBar__results__result")).getText(), is("Não encontramos este termo, verifique a ortografia"));
    driver.get("https://www.webmotors.com.br//");
    driver.findElement(By.id("searchBar")).sendKeys("Toyota");
    driver.findElement(By.cssSelector(".SearchBar__results__result:nth-child(3) strong")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".title-search"));
      assert(elements.size() > 0);
    }
    driver.get("https://www.webmotors.com.br//");
    driver.findElement(By.id("searchBar")).sendKeys("Corolla");
    driver.findElement(By.cssSelector(".SearchBar__results__result:nth-child(3) strong")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".title-search"));
      assert(elements.size() > 0);
    }
    driver.get("https://www.webmotors.com.br//");
    driver.findElement(By.id("searchBar")).sendKeys("Toyota Honda");
    assertThat(driver.findElement(By.cssSelector(".SearchBar__results__result")).getText(), is("Não encontramos este termo, verifique a ortografia"));
    driver.get("https://www.webmotors.com.br//");
    driver.findElement(By.id("searchBar")).sendKeys("Corolla City");
    assertThat(driver.findElement(By.cssSelector(".SearchBar__results__result")).getText(), is("Não encontramos este termo, verifique a ortografia"));
    driver.get("https://www.webmotors.com.br//");
    driver.findElement(By.cssSelector(".Button--red-home")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".title-search"));
      assert(elements.size() > 0);
    }
  }
}
